### ISSUE TITLE
Add mechanism to make sure that always valid JSON data is present in `properties.json`

### ISSUE THREAD

**Issue by thunder-coding** [termux/repology-metadata#1]
This caused Repology to recently stop picking up updates from our repos. The reason was due to a unallowed character in JSON string `"` (the double quotes). It would be great if we can somehow patch our scripts to make sure the JSON is always valid, so that we don't end up in such situation again.

Link to the commit that fixed this:- https://github.com/termux/termux-packages/commit/b760237d8831071490ed9585dc7a8083c940ca2c

**Comment by Grimler91** [comment]
After https://github.com/termux/repology-metadata/commit/2cf97960e30b4b76194fadf502f7ac7849d21deb the CI uses jq to check so that packages.json is valid before uploading new one. Should prevent similar issues
