### ISSUE TITLE
Store more fields in our generated metadata

### ISSUE THREAD

**Issue by thunder-coding** [termux/repology-metadata#2]
Currently we can explore the possibility of adding the following fields to our generated JSON data:-

From https://github.com/termux/termux-packages/commit/b760237d8831071490ed9585dc7a8083c940ca2c#commitcomment-66181066

- package source
- package recipe
- package raw recipe
- package patches
- package raw patches
- (Add more?)

**Comment by Grimler91** [comment]
My suggestion would be to re-write the script in python, to make parsing and json formatting convenient. I can give it a go in a week or two unless someone wants to give it a go before that

**Comment by thunder-coding** [comment]
> My suggestion would be to re-write the script in python, to make parsing and json formatting convenient. I can give it a go in a week or two unless someone wants to give it a go before that

Re-writing the script in python will be a bit of tedious job. Since we are using variables to declare some of our variables in our build scripts. Take for example how `TERMUX_PKG_SRCURL` is normally declared. We'll need to work on a parser which can handle them properly

**Comment by Grimler91** [comment]
@thunder-coding yes, good point, easiest way with python might be to source the file in a subprocess, but then we are anyways back at requiring (ba)sh

**Comment by Grimler91** [comment]
Added in https://github.com/termux/repology-metadata/commit/8aab0de9dec97121db565b4b5bfe159e5a44eb5f
